### ISSUE TITLE
AWS has errors processing certain images

### ISSUE THREAD

**Issue by al1729** [TsotsosLab/SMILER#37]
When running MATLAB models without smoothing on the sample images provided, AWS model running fails on some images but not others. The specific error message is 
```
Index in position 3 exceeds array bounds (must not exceed 1).

Error in aws

Error in AWS_wrap (line 51)
	[~, salmap] = evalc('aws(img,1,2.1)');

[AWS] Error processing image ./clowns.jpg.
```
Steps to reproduce: initialize the below as an experiment.yaml file within SMILER on MacOS, the run SMILER on said file:
```
experiment:
  name: Simple Example
  description: An illustrative example of how to set up SMILER YAML experiments.
  input_path: ./SMILER/examples/input_images
  base_output_path: /tmp/test_out
  parameters:
    do_smoothing: none

runs:

  - algorithm: AWS
    output_path: ./SMILER/smiler_tools/smiler_tools/exp_output/AWS
    parameters:
      do_smoothing: default

```
